name: AQI CI/CD Pipeline

on:
  schedule:
    # Run datafetcher.py every hour
    - cron: "0 * * * *"
    # Run model_trainer.py every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual run

jobs:
  run-datafetcher:
    if: github.event.schedule == '0 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data_fetcher.py
        run: python data_fetcher.py

  run-model-trainer:
    if: github.event.schedule == '0 0 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run model_trainer.py
        run: python model_trainer.py
